server:
  port: 9000

spring:
  application:
    name: polpid_spring_study
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring
    username: spring
    password: spring1!
    validation-query: select 1
    test-while-idle: true
    time-between-eviction-runs-millis: 300000
    test-on-borrow: false
    initialize: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_schema: springstudy
  thymeleaf:
    cache: false
    livereload:
#  devtools:
#      enabled: true
#  freemarker:
#    cache: false

logging:
  level:
    ROOT: info
    org.springframework.security: debug

